name: quran_a_day
description: Quran a day app
version: 3.0.0+3
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  al_quran: ^0.1.1+5
  bloc: ^8.1.4
  day_night_switcher: ^0.2.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.21.2
  flutter_islamic_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  hijri: ^3.0.0
  intl: ^0.20.0
  lamsz_quran_api: ^0.0.4
  quran: ^1.3.3
  quran_flutter: ^1.0.2
  responsive_builder: ^0.7.1
  flex_color_scheme: ^8.1.1
  timings_of_deen: ^0.0.1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icon/icon.png
    # - assets/background.png

flutter_launcher_icons:
  android: "icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
